Models/Developer.cs
using System.ComponentModel.DataAnnotations;

namespace GameStore.Models
{
    public class Developer
    {
        [Key]
        public int DeveloperId { get; set; }
        [Display(Name = "Pictures of the Developer")]
        public String DeveloperPicture { get; set; }
        [Display(Name = "Name of the Developer")]
        public String DeveloperName { get; set; }
        [Display(Name = "Description of the Platforms")]
        public String Description { get; set; }

        public List <Games> Game { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace GameStore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Game.cs
using GameStore.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GameStore.Models
{
    public class Game
    {
        [Key]
        public int GameId { get; set; }
        public String NameOfTheGame { get; set; }
        public String Description { get; set; }
        public double Price { get; set; }
        public String ImageURL { get; set; }
        public DateTime ReleaseDate { get; set; }
        public GameCategory GameCategory { get; set; }

        public List<Platforms_Games> Platforms_Games { get; set; }

        // Publisher 
        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public Publisher Publisher { get; set; }
        
        // Developers
        public int DeveloperId { get; set; }
        [ForeignKey("DeveloperId")]
        public Developer Developer { get; set; }
    }
}

Models/Games.cs
using GameStore.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GameStore.Models
{
    public class Games
    {
        [Key]
        public int GameId { get; set; }
        public String NameOfTheGame { get; set; }
        public String Description { get; set; }
        public double Price { get; set; }
        public String ImageURL { get; set; }
        public DateTime ReleaseDate { get; set; }
        public GameCategory GameCategory { get; set; }

        public List<Platforms_Games> Platforms_Games { get; set; }

        // Publisher 
        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public Publisher Publisher { get; set; }
        
        // Developers
        public int DeveloperId { get; set; }
        [ForeignKey("DeveloperId")]
        public Developer Developer { get; set; }
    }
}

Models/Platforms.cs
using System.ComponentModel.DataAnnotations;

namespace GameStore.Models
{
    public class Platforms
    {
        [Key]
        public int PlatformId { get; set; }

        [Display(Name = "Pictures of the Platform")]
        [Required(ErrorMessage ="Platforms's picture is required!")]
        public String PlatformPicture { get; set; }

        public String PlatformName { get; set; }
        [Display(Name = "Name of the Platform")]
        [Required(ErrorMessage = "Platforms's name is required!")]


        public String Description { get; set; }
        

        public List<Platforms_Games>? Platforms_Games { get; set; }
    }
}

Models/Platforms_Games.cs
namespace GameStore.Models
{
    public class Platforms_Games
    {
        public int GameId { get; set; }
        public Games Game { get; set; }
        public int PlatformId { get; set; }
        public Platforms Platforms { get; set; }
    }
}

Models/Publisher.cs
using System.ComponentModel.DataAnnotations;

namespace GameStore.Models
{
    public class Publisher
    {
        [Key]
        public int PublisherId { get; set; }
        [Display(Name = "Pictures of the Publisher")]
        public String Logo { get; set; }
        [Display(Name = "Name of the Publisher")]
        public String PublisherName { get; set; }
        [Display(Name = "Description of the Publisher")]

        public String Description { get; set; }
        
        public List<Games> Game { get; set; }
    }
}

Controllers/DeveloperController.cs
using GameStore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GameStore.Controllers
{
    public class DeveloperController : Controller
    {
        private readonly AppDbContext _context;
        public DeveloperController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allDevelopers = await _context.Developer.ToListAsync();
            return View(allDevelopers);
        }
    }
}

Controllers/GamesController.cs
using GameStore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GameStore.Controllers
{
    public class GamesController : Controller
    {
        private readonly AppDbContext _context;
        public GamesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allGames = await _context.Game.ToListAsync();
            return View(allGames);
        }
    }
}

Controllers/PlatformsController.cs
using GameStore.Data;
using GameStore.Data.Services;
using GameStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language.Extensions;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace GameStore.Controllers
{
    public class PlatformsController : Controller
    {
        private readonly IPlatformsService _service;
        public PlatformsController(IPlatformsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        // Get: Platforms/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("PlatformPicture,PlatformName,Description")]Platforms platform)
        {
            if(!ModelState.IsValid)
            {
                return View(platform);
            }
            await _service.AddAsync(platform);
            return RedirectToAction(nameof(Index));
        }

        // Get: Platforms / Details
        public async Task<IActionResult> Details(int id)
        {
            var platformDetails = await _service.GetByIdAsync(id);
            if (platformDetails == null) return View("Not Found!");
            return View(platformDetails);
        }

        // Get: Platforms/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var platformDetails = await _service.GetByIdAsync(id);
            if (platformDetails == null) return View("Not Found!");
            return View(platformDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("PlatformsId,PlatformPicture,PlatformName,Description")] Platforms platform)
        {
            if (!ModelState.IsValid)
            {
                return View(platform);
            }
            await _service.UpdateAsync(id,platform);
            return RedirectToAction(nameof(Index));

        }
        // Get: Platforms/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var platformDetails = await _service.GetByIdAsync(id);
            if (platformDetails == null) return View("Not Found!");
            return View(platformDetails);
        }

        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var platformDetails = await _service.GetByIdAsync(id);
            if (platformDetails == null) return View("Not Found!");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

Controllers/PublisherController.cs
using GameStore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GameStore.Controllers
{
    public class PublisherController : Controller
    {
        private readonly AppDbContext _context;
        public PublisherController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allPublisher = await _context.Publisher.ToListAsync();
            return View(allPublisher);
        }
    }
}

Views/Developer/Index.cshtml
@model IEnumerable<Developer>

@{
    ViewData["Title"] = "List of Developers";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class=" text-center">
                    <th>@Html.DisplayNameFor(model =>model.DeveloperPicture)</th>
                    <th>@Html.DisplayNameFor(model =>model.DeveloperName)</th>
                    <th>@Html.DisplayNameFor(model =>model.Description)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.DeveloperPicture " alt="@item.DeveloperName" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.DeveloperName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-secondary"><i class=" bi bi-pencil-square">Edit</i></a>
                            <a class="btn btn-info text-white"><i class=" bi bi-eye">Details</i></a>
                            <a class="btn btn-danger"><i class=" bi bi-trash">Delete</i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Views/Games/Index.cshtml
@model IEnumerable<Games>

@{
    ViewData["Title"] = "List of Games";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.NameOfTheGame
                                    <a class="text-white float-right"><i class="bi bi-pencil-square"></i></a>
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.NameOfTheGame">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Game: </b>@item.NameOfTheGame</p>
                            <p class="card-text"><b>Category: </b>@item.GameCategory</p>
                            <p class="card-text"><b>Release Date: </b>@item.ReleaseDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.ReleaseDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill"></i> Show Details</a>
                                <a class="btn btn-success text-white"><i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Views/Platforms/Create.cshtml
@model Platforms

@{
    ViewData["Title"] = "Add a new Platform";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Platforms</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img id="PlatformPicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformPicture" class="control-label"></label>
                        <input asp-for="PlatformPicture" class="form-control" />
                        <span asp-validation-for="PlatformPicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformName" class="control-label"></label>
                        <input asp-for="PlatformName" class="form-control" />
                        <span asp-validation-for="PlatformName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>
        $(document).ready(function()
        {
            var output = document.getElementById('PlatformPicturePreview');
            output.src = $("#PlatformPictures").val();
        })
        $("#PlatformPicture").on("change", function () {
            var output = document.getElementById('PlatformPicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Views/Platforms/Delete.cshtml
@model Platforms

@{
    ViewData["Title"] = "Delete Platform";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.PlatformName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                
                    
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle " style="max-width:150px;"   id="PlatformPicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformPicture" class="control-label"></label>
                        <input asp-for="PlatformPicture" class="form-control" readonly />
                        <span asp-validation-for="PlatformPicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformName" class="control-label"></label>
                        <input asp-for="PlatformName" class="form-control" readonly/>
                        <span asp-validation-for="PlatformName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" readonly/>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="PlatformId" />
                            <input type="submit" value="Confirm" class="btn btn-danger float-right"/>
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
               
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PlatformPicturePreview');
            output.src = $("#PlatformPictures").val();
        })
    </script>
}

Views/Platforms/Details.cshtml
@model Platforms

@{
    ViewData["Title"] = "Add a new Platform";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.PlatformName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                
                    
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle " style="max-width:150px;"   id="PlatformPicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformPicture" class="control-label"></label>
                        <input asp-for="PlatformPicture" class="form-control" readonly />
                        <span asp-validation-for="PlatformPicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformName" class="control-label"></label>
                        <input asp-for="PlatformName" class="form-control" readonly/>
                        <span asp-validation-for="PlatformName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" readonly/>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.PlatformId">Edit</a>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
               
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PlatformPicturePreview');
            output.src = $("#PlatformPictures").val();
        })
    </script>
}

Views/Platforms/Edit.cshtml
@model Platforms

@{
    ViewData["Title"] = "Update Platform";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Platforms</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle " style="max-width:150px;" id="PlatformPicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformPicture" class="control-label"></label>
                        <input asp-for="PlatformPicture" class="form-control" />
                        <span asp-validation-for="PlatformPicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PlatformName" class="control-label"></label>
                        <input asp-for="PlatformName" class="form-control" />
                        <span asp-validation-for="PlatformName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>
        $(document).ready(function()
        {
            var output = document.getElementById('PlatformPicturePreview');
            output.src = $("#PlatformPictures").val();
        })
        $("#PlatformPicture").on("change", function () {
            var output = document.getElementById('PlatformPicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Views/Platforms/Index.cshtml
@model IEnumerable<Platforms>

@{
    ViewData["Title"] = "List of Platforms";
}

<div class = "row">
    <div class="col-md-8 offset-md-2">
        <table class="table"> 
            <thead>
                <tr class=" text-center">
                    <th>@Html.DisplayNameFor(model =>model.PlatformPicture)</th>
                    <th>@Html.DisplayNameFor(model =>model.PlatformName)</th>
                    <th>@Html.DisplayNameFor(model =>model.Description)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle"src="@item.PlatformPicture" alt ="@item.PlatformName" style="max-width:150px"/>
                        </td>
                        <td class ="align-middle">
                            @Html.DisplayFor(modelItem => item.PlatformName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@item.PlatformId"><i class=" bi bi-pencil-square">Edit</i></a>
                            <a class="btn btn-info text-white" asp-action="Details" asp-route-id="@item.PlatformId"><i class=" bi bi-eye">Details</i></a>
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.PlatformId"><i class=" bi bi-trash">Delete</i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

<div class="text-white" style="position:fixed; right: 25px; bottom:25px;">
    <a asp-controller="Platforms" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"> Add New</i></a>
</div> 

Views/Publisher/Index.cshtml
@model IEnumerable<Publisher>

@{
    ViewData["Title"] = "List of Publishers";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class=" text-center">
                    <th>@Html.DisplayNameFor(model =>model.Logo)</th>
                    <th>@Html.DisplayNameFor(model =>model.PublisherName)</th>
                    <th>@Html.DisplayNameFor(model =>model.Description)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.Logo" alt="@item.PublisherName" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.PublisherName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-secondary"><i class=" bi bi-pencil-square">Edit</i></a>
                            <a class="btn btn-info text-white"><i class=" bi bi-eye">Details</i></a>
                            <a class="btn btn-danger"><i class=" bi bi-trash">Delete</i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Games" asp-action="Index">GameStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Games" asp-action="Index"><i class="bi bi-controller"></i> Games</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Games" asp-action="Index"><i class="bi bi-controller"></i> Games</a>
                                <a class="dropdown-item" asp-controller="Publsihers" asp-action="Index"><i class="bi bi-camera"></i> Publisher</a>
                                <a class="dropdown-item" asp-controller="Platforms" asp-action="Index"><i class="bi bi-person-square"></i> Platforms</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-check-inline my-2 my-lg-0" asp-controller ="Games" asp-action="Filter" style="padding-right:25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for game..">
                        <button class="btn btn-outline-success my-2 my-sm-0" tpye="submit"> <i class="bi bi-search float-right"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameStore 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>